# Partner Distribution Configuration File
# Author: Mozilla
# Date: 2015-03-27

[Global]
id=firefox-enterprise
version=1.0
about=Mozilla Firefox Enterprise

[Preferences]
media.eme.enabled=false
app.partner.mozilla-EMEfree="mozilla-EMEfree"
